### ISSUE TITLE
Unable to read application.properties from file system backend(Section 15)

### ISSUE THREAD

**Issue by shivaram549** [madhurkumar/fullstacktraining#3]
**Application.properties:**

spring.application.name=PhotoAppAPIConfigServer
server.port=8012
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file://${user.home}/Desktop/dev
spring.cloud.config.server.git.uri=https://github.com/shivaram549/PhotoAppConfigurationServer
spring.cloud.config.server.git.username=shivaram549
spring.cloud.config.server.git.password=*****
spring.cloud.config.server.git.clone-on-start=true

**Json Request:** 
 http://localhost:8012/PhotoAppAPIConfigServer/native

**Response:**
{
    "name": "PhotoAppAPIConfigServer",
    "profiles": [
        "native"
    ],
    "label": null,
    "version": null,
    "state": null,
    "propertySources": []
}

here, propertySources must have all the properties mentioned in the local file. But it's showing empty.

**Comment by RanjithReddyNimma** [comment]
Replace  **spring.cloud.config.server.native.searchLocations**=file:///${user.home}/Desktop/dev will work

**Comment by shivaram549** [comment]
Thanks Ranjith! It's working.

**Comment by madhurkumar** [comment]
Great job team.
